namespace Relay.Documentum.Domain.Aggregates;

public sealed record EdgeOrder(
    string OrderGuid,
    int OrderSeq,
    string? Brand,
    string? RepPO,
    string? AccountNumber,
    DateTime? OrderDate,
    string? RepCustomer,
    string? RepUserName,
    string? RepSalesPerson,
    string? JobNumber,
    string? Status,
    string TotalNet,
    DateTime? OrderRecdDate,
    string? SalesOrderNumber,
    int? Priority,
    string? RepName,
    string? QueueName,
    string? ProductType,
    string? Region,
    string? JobName,
    DateTime? CreatedDate,
    DateTime? CompletionDate,
    string? PackageOwner);
